### ISSUE TITLE
What tools do you use for font subsetting?

### ISSUE THREAD

**Issue by KyleAMathews** [zachleat/ama#4]

**Comment by zachleat** [comment]
If it’s a font icon, I’ve had good luck with [`Font Prep`](https://github.com/briangonzalez/fontprep) which is a very visual tool. (Make sure you subset your CSS too!)

@roeln has a great blog post about how he optimized the Font Awesome icon font, which is worth a read: https://pixelambacht.nl/2016/font-awesome-fixed/

If I want ultimate power and super reduced file size, I was turned on to `pyftsubset` from [`fonttools`](https://github.com/fonttools/fonttools) by @roeln.

It can be a pain to configure the command, but here’s a nice sample command I’ve used that might help get you started:

```
pyftsubset --glyphs=exclam,quotedbl,numbersign,dollar,percent,ampersand,quotesingle,parenleft,parenright,asterisk,plus,comma,hyphen,period,slash,zero,one,two,three,four,five,six,seven,eight,nine,colon,semicolon,less,equal,greater,question,at,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,bracketleft,bracketright,asciicircum,underscore,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,braceleft,bar,braceright,asciitilde,space,copyright,multiply,ntilde,quoteleft,quoteright,ellipsis,quotedblleft,quotedblright --verbose --flavor=woff
```

`--flavor=woff2` works great too.
